# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/JX3HDUnpackerL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/JX3HDUnpackerL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/JX3HDUnpackerL/CMakeFiles /root/JX3HDUnpackerL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/JX3HDUnpackerL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JX3HDUnpackerL

# Build rule for target.
JX3HDUnpackerL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JX3HDUnpackerL
.PHONY : JX3HDUnpackerL

# fast build rule for target.
JX3HDUnpackerL/fast:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/build
.PHONY : JX3HDUnpackerL/fast

INIReader.o: INIReader.cpp.o

.PHONY : INIReader.o

# target to build an object file
INIReader.cpp.o:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/INIReader.cpp.o
.PHONY : INIReader.cpp.o

INIReader.i: INIReader.cpp.i

.PHONY : INIReader.i

# target to preprocess a source file
INIReader.cpp.i:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/INIReader.cpp.i
.PHONY : INIReader.cpp.i

INIReader.s: INIReader.cpp.s

.PHONY : INIReader.s

# target to generate assembly for a file
INIReader.cpp.s:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/INIReader.cpp.s
.PHONY : INIReader.cpp.s

JX3HDUnpackerL.o: JX3HDUnpackerL.cpp.o

.PHONY : JX3HDUnpackerL.o

# target to build an object file
JX3HDUnpackerL.cpp.o:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/JX3HDUnpackerL.cpp.o
.PHONY : JX3HDUnpackerL.cpp.o

JX3HDUnpackerL.i: JX3HDUnpackerL.cpp.i

.PHONY : JX3HDUnpackerL.i

# target to preprocess a source file
JX3HDUnpackerL.cpp.i:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/JX3HDUnpackerL.cpp.i
.PHONY : JX3HDUnpackerL.cpp.i

JX3HDUnpackerL.s: JX3HDUnpackerL.cpp.s

.PHONY : JX3HDUnpackerL.s

# target to generate assembly for a file
JX3HDUnpackerL.cpp.s:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/JX3HDUnpackerL.cpp.s
.PHONY : JX3HDUnpackerL.cpp.s

ini.o: ini.c.o

.PHONY : ini.o

# target to build an object file
ini.c.o:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/ini.c.o
.PHONY : ini.c.o

ini.i: ini.c.i

.PHONY : ini.i

# target to preprocess a source file
ini.c.i:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/ini.c.i
.PHONY : ini.c.i

ini.s: ini.c.s

.PHONY : ini.s

# target to generate assembly for a file
ini.c.s:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/ini.c.s
.PHONY : ini.c.s

zip.o: zip.c.o

.PHONY : zip.o

# target to build an object file
zip.c.o:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/zip.c.o
.PHONY : zip.c.o

zip.i: zip.c.i

.PHONY : zip.i

# target to preprocess a source file
zip.c.i:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/zip.c.i
.PHONY : zip.c.i

zip.s: zip.c.s

.PHONY : zip.s

# target to generate assembly for a file
zip.c.s:
	$(MAKE) -f CMakeFiles/JX3HDUnpackerL.dir/build.make CMakeFiles/JX3HDUnpackerL.dir/zip.c.s
.PHONY : zip.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... JX3HDUnpackerL"
	@echo "... INIReader.o"
	@echo "... INIReader.i"
	@echo "... INIReader.s"
	@echo "... JX3HDUnpackerL.o"
	@echo "... JX3HDUnpackerL.i"
	@echo "... JX3HDUnpackerL.s"
	@echo "... ini.o"
	@echo "... ini.i"
	@echo "... ini.s"
	@echo "... zip.o"
	@echo "... zip.i"
	@echo "... zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

